spring:
  thymeleaf:
    prefix=classpath: templates/
    suffix: .html
    cache: false
    check-template-location: true
  mvc:
    static-path-pattern: "/static/**"
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://donipop.com:3306/livestreaming?useUnicode=true&serverTimezone=Asia/Seoul
      username: doni
      password: 1234
      pool-name: TestHikariPool

server:
  port: 2313