spring:
  thymeleaf:
    prefix=classpath: templates/
    suffix: .html
    cache: false
    check-template-location: true
  mvc:
    static-path-pattern: "/static/**"
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://52.78.162.166:54994/livestreaming?useUnicode=true&serverTimezone=Asia/Seoul
      username: doni
      password: 1234
      pool-name: TestHikariPool
  devtools:
    livereload:
      enabled: true
mybatis:
  type-aliases-package: com.donipop.livestreaming.model.dto

server:
  port: 2313